// types.js

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CURRENT_USER_INFO = 'CURRENT_USER_INFO';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const OPEN_PROJECT_MODAL = 'OPEN_PROJECT_MODAL';
export const CLOSE_PROJECT_MODAL = 'CLOSE_PROJECT_MODAL';
export const NEW_PROJECT_CREATED = 'NEW_PROJECT_CREATED';
